version: '3'
services:
  app:
    build: ./
    command: pipenv run start
    ports:
      - 5000:5000
    volumes:
      - ./:/var/www/html
      - packages:/root/.local/share

volumes:
  packages:
    driver: local